# Generated by Django 4.2 on 2023-06-29 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myimages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myimages',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
